//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smbxnpceditor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("smbxnpceditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap e7d7d8db2773f0e53d7407cffd9bb6f4 {
            get {
                object obj = ResourceManager.GetObject("e7d7d8db2773f0e53d7407cffd9bb6f4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap notanicon {
            get {
                object obj = ResourceManager.GetObject("notanicon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ; Generated on 7/16/2014 12:17:26 PM
        ///[npcconfig]
        ///name=SMBX64
        ///description=The default set of SMBX NPC&apos;s
        ///npc-1=Goomba
        ///npc-2=Red Goomba
        ///npc-3=Red Winged Goomba
        ///npc-4=Green Koopa (SMB3)
        ///npc-5=Green Koopa Shell (SMB3)
        ///npc-6=Red Koopa
        ///npc-7=Red Koopa Shell (SMB3)
        ///npc-8=Pirahna Plant (SMB3)
        ///npc-9=Red Mushroom (SMB3)
        ///npc-10=Gold Coin (SMB3)
        ///npc-11=SMB3 Exit
        ///npc-12=Podobo (SMB3)
        ///npc-13=Player Fireballs
        ///npc-14=Fire Flower (SMB3)
        ///npc-15=Boom-Boom
        ///npc-16=Exit Orb (SMB3)
        ///npc-17=Bullet Bill (SMB3)
        ///np [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SMBX64 {
            get {
                return ResourceManager.GetString("SMBX64", resourceCulture);
            }
        }
    }
}
